#!/bin/bash

set -x

# functies
function method_telegram {
    # input for variables
    TELEGRAM_CHAT_ID="-306261393"
    TELEGRAM_URL="https://api.telegram.org/bot602094817:AAHxbZtXbgpNLMRb0LfpZ2uZpOPrjX86cfc/sendMessage"

    # create payload for Telegram
    TELEGRAM_PAYLOAD="chat_id=${TELEGRAM_CHAT_ID}&text=${TELEGRAM_MESSAGE}&parse_mode=Markdown&disable_web_page_preview=true"

    # sent payload to Telegram API and exit
    curl -s --max-time 10 --retry 5 --retry-delay 2 --retry-max-time 10 -d "${TELEGRAM_PAYLOAD}" "${TELEGRAM_URL}" > /dev/null 2>&1 &
}

# locatie logfiles definieren
LOCATION_LOGFILES=/var/lib/diskspace

# logfiles aanpassen naar vandaag
rm ${LOCATION_LOGFILES}/yesterday.txt
mv ${LOCATION_LOGFILES}/today.txt ${LOCATION_LOGFILES}/yesterday.txt

# huidige waardes uitvragen en wegschrijven
PREVIOUS_VALUE="$(cat ${LOCATION_LOGFILES}/yesterday.txt)"
CURRENT_VALUE="$(($(df / --output="used" | sed -n '2 p' | tr -dc '1234567890.')/1024))"
touch "${LOCATION_LOGFILES}/today.txt"
echo "${CURRENT_VALUE}" >> "${LOCATION_LOGFILES}/today.txt"


# waardes vergelijken met vorige keer en bericht genereren
if (( ${CURRENT_VALUE} > ${PREVIOUS_VALUE} )); then
    DIFFERENCE="$((${CURRENT_VALUE} - ${PREVIOUS_VALUE}))"
    DIFFERENCE_MESSAGE="De gebruikte schijfruimte is dus met ${DIFFERENCE} MB toegenomen."
elif (( ${CURRENT_VALUE} < ${PREVIOUS_VALUE} )); then
    DIFFERENCE="$((${PREVIOUS_VALUE} - ${CURRENT_VALUE}))"
    DIFFERENCE_MESSAGE="De gebruikte schijfruimte is dus met ${DIFFERENCE} MB afgenomen."
elif (( ${CURRENT_VALUE} == ${PREVIOUS_VALUE} )); then
    DIFFERENCE="0"
    DIFFERENCE_MESSAGE="De gebruikte schijfruimte is dus exact evenveel als de vorige keer."
else
    DIFFERENCE_MESSAGE="Er is iets misgegaan (foutcode #01). Vraag uw systeembeheerder dit probleem op te lossen."
fi

MESSAGE="De vorige keer was uw gebruikte schijfruimte: ${PREVIOUS_VALUE} MB.\\nNu is uw gebruikte schijfruimte: ${CURRENT_VALUE} MB.\\n${DIFFERENCE_MESSAGE}"
echo -e ${MESSAGE}


# add values to method_telegram variables
    TELEGRAM_MESSAGE="$(echo -e ${MESSAGE})"

    # call method_telegram
    method_telegram

    # exit when done
    exit 0




#set -x
